#ifndef COMMON_COMMON_H_
#define COMMON_COMMON_H_
namespace frontend::common {

constexpr size_t kCharNum = CHAR_MAX - CHAR_MIN + 1;

}

#ifdef _DEBUG

#define USE_PRODUCTION_NODE_USER_DATA
#define USE_PRODUCTION_NODE_INIT_FUNCTION
#define USE_PRODUCTION_NODE_REDUCTION_FUNCTION
#define USE_TERMINAL_NODE_SHIFT_FUNCTION
#define USE_NONTERMINAL_NODE_SHIFT_FUNCTION
#define USE_OPERATOR_NODE_SHIFT_FUNCTION

#endif  // _DEBUG

#endif  // !COMMON_COMMON_H_
